### ISSUE TITLE
[BUG] TYPO3 backend admin account get lost

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/solr-ddev-site#11]
**Describe the bug**
Sometimes the TYPO3 backend admin account get lost after starting ddev `ddev start`.
How ever the database and the Solr test content is existing.

_Note:_ This bug does not appear all the time. May be it effects by other ddev projects.

**To Reproduce**

1. Run `ddev stop --remove-data --omit-snapshot`
2. Run `ddev start`.
3. Open http://solr-ddev-site.ddev.site/typo3/
4. Try to login with `admin`
5. Check PhpMyAdmin if the admin account is available

**Expected behavior**
The admin account should be available after run `ddev start`

**Used versions (please complete the following information):**
 - solr-ddev-site Version: 1.1.0
 - ddev Version: v1.16.2

**Comment by dkd-kaehm** [comment]
OK, I'll watch for this behavior and will use `ddev stop + start` a little bit frequenter.

**Comment by 3l73** [comment]
Note: Even the Solr Indexer scheduler task is not available

**Comment by dkd-kaehm** [comment]
@3l73 
plaese don't use `ddev stop --remove-data --omit-snapshot` but use `ddev clean` instead, which resets/cleans the stuff needed for kicking the "initial" installation steps.
I do not see currently a clean way to setup ddev for triggering the installation steps by using original ddev commands.

---

See the files, which presence leads to this behaviour:

https://github.com/TYPO3-Solr/solr-ddev-site/blob/5b979f76b327b39d8004e560a571ad847626cd15/.ddev/commands/host/clean#L5-L23

---

May be we want some option for this command to leave the composer/PHP libs untouched.

**Comment by dkd-kaehm** [comment]
@3l73 
Do you have ideas?

**Comment by 3l73** [comment]
> @3l73
> Do you have ideas?

ddev supports different hooks we can use to insert an admin account.

Following looks promising:

- post-start
- post-composer
- post-import-db

These hooks can trigger following command
- `vendor/bin/typo3cms <username> <password>`

More information about hooks:
- https://ddev.readthedocs.io/en/stable/users/extending-commands/
