### ISSUE TITLE
[BUG] PHP error "Solarium\Core\Client\Adapter\Psr18Adapter' not found" occurs when running inside the release-11.0.x branch

### ISSUE THREAD

**Issue by dkdjpiltz** [TYPO3-Solr/solr-ddev-site#23]
**Describe the bug**
When starting ddev outside of the master branch, the ext-solr extension is not in lock-step with the solr-ddev-site branch resulting in a PHP error "Class 'Solarium\Core\Client\Adapter\Psr18Adapter' not found" when opening the Report or any Solr module inside the TYPO3 backend.

**To Reproduce**
1. Clone this repository
2. Checkout any other branch than master, ex. release-11.0.x
3. Run the command `ddev start`

When the host clone command for ext-solr runs following message is printed:

> The branch release-11.0.x of current solr-ddev-site project does not exist on ext-solr

(Leaving ext-solr in the master branch)

4. Inside the TYPO3 backend open the module _Reports_ or any _Solr_ module. Following PHP error occurs:

> Class 'Solarium\Core\Client\Adapter\Psr18Adapter' not found

**Expected behavior**
The TYPO3 backend modules _Reports_ and _Solr_ should not result in a PHP error (the ext-solr extension/package should be in lock-step with the solr-ddev-site branch currently in use). 

**Used versions (please complete the following information):**
 - solr-ddev-site branch or commit: release-11.0.x
 - ddev Version: 1.17.7
 - Operating system: mac
 - Operating system version: Catalina

**Additional context**
The clone command inside .ddev/commands/host/ clones the ext-solr repository alright. At that point only the master branch of ext-solr is available locally. Hence the subsequent test for a branch matching the current solr-ddev-site branch always fails outside of the master branch, because `git branch --list` only lists the locally available branches.

**Comment by dkd-kaehm** [comment]
We want Ports into master and others.

**Comment by dkdjpiltz** [comment]
I left out the task and feature branches
